/*
 * Tencent DLC CLI
 * Copyright (C) 2026 Bing Tong and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.tencent.dlc.cli.command;

import picocli.AutoComplete;
import picocli.CommandLine;

import java.io.PrintWriter;
import java.util.concurrent.Callable;

/**
 * Generates a shell completion script for the tdlc CLI.
 */
@CommandLine.Command(
    name = "completion",
    description = "Generate a shell completion script"
)
public class CompletionCommand implements Callable<Integer> {

    @CommandLine.Spec
    private CommandLine.Model.CommandSpec spec;

    @CommandLine.Parameters(
        index = "0",
        description = "Shell to generate completions for: bash or zsh"
    )
    private String shell;

    @Override
    public Integer call() {
        if (shell == null || shell.isEmpty()) {
            spec.commandLine().getErr().println("Error: shell argument is required (bash or zsh)");
            return 1;
        }

        String shellLower = shell.toLowerCase();
        if (!shellLower.equals("bash") && !shellLower.equals("zsh")) {
            spec.commandLine().getErr().println("Error: unsupported shell '" + shell + "'. Use bash or zsh.");
            return 1;
        }

        PrintWriter out = spec.commandLine().getOut();
        try {
            String script = AutoComplete.bash("tdlc", spec.root().commandLine());
            if (shellLower.equals("zsh")) {
                script = convertToZsh(script);
            }
            out.println(script);
        } catch (Exception e) {
            spec.commandLine().getErr().println("Error: failed to generate completion script: " + e.getMessage());
            return 1;
        }

        out.flush();
        return 0;
    }

    /**
     * Converts the picocli bash completion script into a form usable by zsh's
     * bashcompinit. The bash script generated by picocli is pure bash functions
     * and uses the bash built-in `complete`; zsh can load this after running
     * `bashcompinit`, so the conversion is minimal: we just wrap the script
     * with a guard that ensures bashcompinit is loaded.
     */
    private static String convertToZsh(String bashScript) {
        StringBuilder zshScript = new StringBuilder();
        zshScript.append("#compdef tdlc\n\n");
        zshScript.append("autoload -U +X bashcompinit && bashcompinit\n\n");
        zshScript.append(bashScript);
        return zshScript.toString();
    }
}
