source.. = src/
output.. = target/classes/
bin.includes = .,\
               META-INF/,\
               plugin.xml,\
               icons/,\
               lib/,\
               lib/dlc-core-1.0.0-SNAPSHOT.jar
